# crude hackjob
# refer for cleanup https://github.com/envygeeks/jekyll-docker/blob/master/README.md

volumes:
  gems:
# ===
x-base: &jekyll-base
    image: jekyll/jekyll
    volumes:
      - ./:/srv/jekyll
      - gems:/usr/gem
# ===
services:
  dev:
    <<: *jekyll-base
    ports:
      - "127.0.0.1:4000:4000"
    command: jekyll serve

  update:
    <<: *jekyll-base
    command: bundle update
    profiles:
      - update

